# Generated by Django 2.0.4 on 2018-04-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='folders.Folder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='profiles.Profile')),
            ],
        ),
    ]
