# Generated by Django 2.0.4 on 2018-05-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='description',
            new_name='preview',
        ),
    ]
