# Generated by Django 2.0.4 on 2018-05-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180501_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='preview',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='link',
            name='folder',
        ),
        migrations.AddField(
            model_name='link',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.Folder'),
        ),
    ]
