# Generated by Django 2.0.4 on 2018-05-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20180504_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='icon',
            new_name='image_url',
        ),
    ]
