# Generated by Django 2.0.4 on 2018-05-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20180509_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
