# Generated by Django 2.0.4 on 2018-05-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_collections'),
        ('links', '0008_auto_20180513_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folders.Collection'),
        ),
    ]
