# Generated by Django 2.0.4 on 2018-05-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_link_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='collection',
        ),
        migrations.AddField(
            model_name='link',
            name='domain',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
