# Generated by Django 2.0.4 on 2018-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_auto_20180515_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.CharField(max_length=255),
        ),
    ]
