# Generated by Django 2.0.4 on 2018-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_auto_20180515_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
